### ISSUE TITLE
使用中发现NetUtils的isWifi在wifi和数据全部断时会fc

### ISSUE THREAD

**Issue by dreamcontinue** [h4de5ing/AndroidCommon#1]

**Comment by h4de5ing** [comment]
能否贴一下使用的代码片段。

**Comment by dreamcontinue** [comment]
当wifi和数据全断开时，直接调用`NetUtils.isWifi(context)`
错误信息： Attempt to invoke virtual method 'int android.net.NetworkInfo.getType()' on a null object reference
换成(NetUtils.isConnected(context)&&NetUtils.isWifi(Context))可以解决。
