### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by hsiunien** [h4de5ing/AndroidCommon#2]
谢谢博主提供一个工具类，自己也写过，没有博主分类这么细致。非常感谢，但由于只用到部分功能，因此拷贝了部分代码到我们项目中。
建议每个方法加上readme 中的注释。

https://github.com/h4de5ing/AndroidCommon/blob/master/library/src/main/java/com/code19/library/StringUtils.java#L142 
这一行 str.trim().length() == 0 || "".equals(str); 后面那个或语句可以忽略掉。

**Comment by h4de5ing** [comment]
fixed,StringUtils.java#L142 程序员应该避免写注释，我已经将方法名称和参数名称写的尽可能表达出他的功能了。
