### ISSUE TITLE
7.0以上版本限制了 file://URI的传递，AppUtils的installApk方法最好做一下版本判断吧

### ISSUE THREAD

**Issue by b4nst0n** [h4de5ing/AndroidCommon#3]
sdk24以下的继续沿用原有方法，大于等于24的可以交给开发者自己处理，不太会用github，不知道怎么提pullrequest ;p

**Comment by h4de5ing** [comment]
对installApk 和uninstallApk方法添加Deprecated注解。

**Comment by FangWW** [comment]
😢  新锅 你好歹要把他兼容了阿
