### ISSUE TITLE
bug阿

### ISSUE THREAD

**Issue by FangWW** [h4de5ing/AndroidCommon#4]
[L.java](https://github.com/h4de5ing/AndroidCommon/blob/master/library/src/main/java/com/code19/library/L.java) 不能打长日志阿  老只有一半阿  坑爹阿

**Comment by h4de5ing** [comment]
[Fixed](https://github.com/h4de5ing/AndroidCommon/commit/abbc53dc3d6bae05589c2696e5c30838e481cb14)
